services:
  - type: web
    name: pushup-tracker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    branch: main
    autoDeployTrigger: off
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: APP_PUBLIC_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: NEXT_PUBLIC_ENABLE_REVIEW_ROUTES
        value: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
  - type: web
    name: pushuptracker-staging
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    branch: staging
    autoDeployTrigger: off
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: APP_PUBLIC_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: NEXT_PUBLIC_ENABLE_REVIEW_ROUTES
        value: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
